### ISSUE TITLE
Could you please consider adding a way to generate inline critical css as well?

### ISSUE THREAD

**Issue by sanishkr** [oddstronaut/next-starter-tailwind#37]

**Comment by taylorbryant** [comment]
@sanishkr This is a great idea. I haven’t found a good way to do this in Next.js. Any ideas?

**Comment by taylorbryant** [comment]
@sanishkr Looks like there's a PR up on Next.js to add an experimental flag that does this: https://github.com/vercel/next.js/pull/16539. 🎉

**Comment by sanishkr** [comment]
Thanks @taylorbryant ,
for now, I did a [setup of my own using `styled-components` and  `twin.macro`](https://github.com/sanishkr/next-tailwind-styled-components).
